<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Clients\Module'                     => __DIR__ . '/Module.php',
    'Clients\Controller\IndexController' => __DIR__ . '/src/Clients/Controller/IndexController.php',
    'Clients\Model\ModelClients'         => __DIR__ . '/src/Clients/Model/ModelClients.php',
    'News\Model\ModelUtils'              => __DIR__ . '/src/Clients/Model/ModelUtils.php',
    'Clients\Form\Search'                => __DIR__ . '/src/Clients/Form/Search.php',
);