<?php
//$form->setAttribute('action', $this->url('clients/index'))->prepare();
//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('csrf'));
//echo $this->formRow($form->get('search'));
////echo $this->formElement($form->get('captcha'));
//echo $this->formRow($form->get('submit'));
////echo $this->formRow($form->get('price'));
////echo '<div>'.$this->formRow($form->get('submit')).'</div>';
////echo "<div></div>";
////echo $this->formRow($form->get('submit'));
//echo $this->form()->closeTag();