<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'News\Model\ModelUtils'               => __DIR__ . '/src/Debitors/Model/ModelUtils.php',
    'Clients\Model\ModelClients'          => __DIR__ . '/src/Debitors/Model/ModelClients.php',
    'Debitors\Controller\IndexController' => __DIR__ . '/src/Debitors/Controller/IndexController.php',
    'Clients\Form\Search'                 => __DIR__ . '/src/Debitors/Form/Search.php',
    'Debitors\Module'                     => __DIR__ . '/Module.php',
);