
<?php //echo "\n<!-- MENU -->\n"?>
<?php //echo $this->headLink()->appendStylesheet($this->baseUrl('css/menu.css')); ?>

<div id="navigation"><ul>
<?php
print_r($this->container);
foreach ($this->container as $page) {
	$res="<li>". $this->navigation()->menu()->htmlify($page).'</li>';
	$res=str_replace('_(','<span>',$res);$res=str_replace(')','</span>',$res);
	echo $res,PHP_EOL;
}
?>
</ul></div>
<?php echo "<!-- /MENU -->\n"?>